name: work-1
on:
  push:
    branches:
      - main
jobs:
  hello1:
    runs-on: ubuntu-latest
    steps:
      - name: sayHi
        run: echo "Hi"
      - name: sayMyName
        run: echo "${{ github.actor }}"
      - name: sayMyref
        run: echo "${{ github.workflow_ref }}"
  hello2:
    runs-on: ubuntu-latest
    steps:
      - name: sayHelloWorld
        run: echo "HelloWorld"
      - name: sayMyName
        run: echo "${{ github.actor }}"
      - name: sayMyref
        run: echo "${{ github.workflow_ref }}"
